#!/bin/sh

printf '\033[1;37;40m               .:/++++/:.`               \033[0m
\033[1;37;40m          `:sdNNdyssssyhmNmy/`           \033[0m
\033[1;37;40m        -yNms:`        ..`-odMh/         \033[0m
\033[1;37;40m      .hMh:      -+shmNNNmo. .sNm/`.-:`  \033[0m
\033[1;37;40m     +Mm-       :Mm+:-` `/hNdhdNMMNmMM.  \033[0m
\033[1;37;40m    sMh`       -NN.    --  `::-.`  :Md   \033[0m
\033[1;37;40m   /Md        -NN-    `MN         .mM-   \033[0m
\033[1;37;40m   mM-      `sMd..do   MM`      `oNMM.   \033[0m
\033[1;37;40m  .Mm     `oNm/  yM+   NM`    -sNm+yM+   \033[0m
\033[1;37;40m  -Md   `+NN+   `MN`   mM::+yNNy:  oMo   \033[0m
\033[1;37;40m  `NN` +mNo`    :Md    dMmdy+-     hM:   \033[0m
\033[1;37;40m   sMymNo`      .Mm`   hM:        -Mm    \033[0m
\033[1;37;40m   `mMd`         oMh.  yM/       .mN-    \033[0m
\033[1;37;40m    `dMo          /dMhodM+      :NN:     \033[0m
\033[1;37;40m      oMd:          NMsss-    -yMh.      \033[0m
\033[1;37;40m       .sNmo-       NM`    .+hMh:        \033[0m
\033[1;37;40m         `/hNNho/:-.NM//oymNdo.          \033[0m
\033[1;37;40m             -/oyhdmmddys+-`             \033[0m\n\n'
